### ISSUE TITLE
dubbo3整合rest和dubbo两种协议

### ISSUE THREAD

**Issue by YIminta** [MartinDai/SpringBoot-Project#17]
大佬，可以整一个同时支持两种协议的 Demo 吗，我研究了好久
官方文档地址
https://cn.dubbo.apache.org/zh/blog/2019/07/26/%E5%9C%A8-dubbo-%E4%B8%AD%E4%BD%BF%E7%94%A8-rest/

我的demo地址：https://github.com/YIminta/duboo3.0-demo
master分支是xml模式 dubbo 版本3.0.7，跑不起
rest分支是注解模式 dubbo 版本2.7.5，能启动但是dubbo-admin不能测试，提示需要dubbo2.6+。
![image](https://user-images.githubusercontent.com/50685567/209094362-7617ce23-7e90-4389-9721-8a40c8d5c5c4.png)

**Comment by MartinDai** [comment]
可以，等我有空研究下

**Comment by MartinDai** [comment]
@YIminta 已实现
